### ISSUE TITLE
how to use MOEA-Framework 2.12 with PSO

### ISSUE THREAD

**Issue by TomlovesJerrys** [MOEAFramework/MOEAFramework#139]
I am trying to use MOEA - Framework 2.12 with SMPSO but i had an error.

Exception in thread "main" org.moeaframework.core.spi.ProviderNotFoundException: no provider for SMPSO
	at org.moeaframework.algorithm.StandardAlgorithms.getAlgorithm(StandardAlgorithms.java:331)
	at org.moeaframework.core.spi.AlgorithmFactory.instantiateAlgorithm(AlgorithmFactory.java:175)
	at org.moeaframework.core.spi.AlgorithmFactory.getAlgorithm(AlgorithmFactory.java:137)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:785)
	at org.moeaframework.Executor.runSeeds(Executor.java:722)
	at MOEA.RunSignalsBlenderProblem.main(RunSignalsBlenderProblem.java:50)
Caused by: org.moeaframework.core.FrameworkException: unsupported decision variable type
	at org.moeaframework.algorithm.StandardAlgorithms.newSMPSO(StandardAlgorithms.java:828)
	at org.moeaframework.algorithm.StandardAlgorithms.getAlgorithm(StandardAlgorithms.java:295)
	... 5 more

Please help me with error.

**Comment by Amit-1984** [comment]
@TomlovesJerrys  can you please guide me in using moea for solving pso based problem.
