### ISSUE TITLE
Custom Operators for JSON

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#173]
Hi @dhadka,

From a previous issue  https://github.com/MOEAFramework/MOEAFramework/issues/170 I asked about the possibility of using JSON format as a the representation for my problem. You pointed out that it was possible, but I had to write mutation and crossover functions that could operate on JSON files. I have attempted that but my first run of the algorithm gives the error below. Can you please point me in the direction of what I am doing incorrectly i.e.  why the 

```
feasibleRoutes = 
[jsonDecisionVariable.txt](https://github.com/MOEAFramework/MOEAFramework/files/1924853/jsonDecisionVariable.txt) 

// this is a sample of 1 decision variable in JSON format

```
```
Exception in thread "main" java.lang.NullPointerException
	at org.moeaframework.core.operator.RandomInitialization.initialize(RandomInitialization.java:62)
	at org.moeaframework.algorithm.AbstractEvolutionaryAlgorithm.initialize(AbstractEvolutionaryAlgorithm.java:97)
	at org.moeaframework.algorithm.AbstractAlgorithm.step(AbstractAlgorithm.java:159)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:816)
	at org.moeaframework.Executor.run(Executor.java:743)
	at org.matsim.onnene.ga.RunSboProblem.main(RunSboProblem.java:81)

```
```
public class SboDecisionVariable implements  Variable{

	private static final long serialVersionUID = 1646704078346725718L;
	private List feasibleRoutes; 
	private JSONObject selectedRoutes; 
	
	public SboDecisionVariable() {
		super();
	}
	
	public SboDecisionVariable(List feasibleRoutes) {
		this();
		this.feasibleRoutes = feasibleRoutes;
	}
	
	protected List getfeasibleRoutes() {
		return feasibleRoutes;
	}

	protected void setfeasibleRoutes(List feasibleRoutes) {
		this.feasibleRoutes = feasibleRoutes;
	}

	@Override
	public Variable copy() {
	SboDecisionVariable copy = new SboDecisionVariable(feasibleRoutes);
        copy.selectedRoutes = new JSONObject(selectedRoutes); 
	}

	@Override
	public void randomize() {
		JSONObject decisionVar  = new JSONObject(PRNG.nextItem(feasibleRoutes));
		selectedRoutes = decisionVar;
}
```
```
    @Override
    public Solution newSolution() {
        Solution solution = new Solution(1, 1);
         for (int i = 1; i < getNumberOfVariables(); i++) {
             solution.setVariable(i, new SboDecisionVariable(feasibleRoutes));
         }
        return solution;
    }

```
```
public class RunSboProblem{

public static void main(String[] args) throws Exception {

      OperatorFactory.getInstance().addProvider(new SboProvider());
	        NondominatedPopulation result = new Executor()
	            .withProblemClass(SboProblem.class)
	            .withAlgorithm("NSGAII")
	            .withProperty("operator", "SboCrossover+SboMutation")
	            .withProperty("MyCrossover.Rate", 0.9)
	            .withProperty("MyMutation.Rate", 0.25)
	            .withMaxEvaluations(MAX_MOEA_EVALUATIONS)
	            .run();

   }
}

```
```
public static void applyCrossover(SboDecisionVariable variable1, SboDecisionVariable variable2) {
		
	   JSONObject var1 = new JSONObject(variable1);
	   JSONObject transitSchedule1 = (JSONObject) var1.get("transitSchedule");
	   JSONArray  transitLine1 = transitSchedule1.getJSONArray("transitLine");
	
	   JSONObject var2 = new JSONObject(variable2);
	   JSONObject transitSchedule2 = (JSONObject) var2.get("transitSchedule");
	   JSONArray  transitLine2 = transitSchedule2.getJSONArray("transitLine");
	   
		  
		  if  (var1!=null && var1.length()>0 && var2!=null && var2.length()>0) {

			  for (int i = 0; i < 20; i++) {
				 transitLine1.remove(i);
				 transitLine1.put(transitLine2.get(i));
				 transitLine2.remove(i);
				 transitLine2.put(transitLine1.get(i));		  
			  }		
		  }
	}
```
```
public static void evolve(SboDecisionVariable variable, List feasibleRoutes) throws IOException {

	  JSONObject var = new JSONObject(variable);
	  JSONObject transitSchedule1 = (JSONObject) var.get("transitSchedule");
	  JSONArray  transitLine1 = transitSchedule1.getJSONArray("transitLine");
   	  JSONObject randRoutes = new JSONObject(PRNG.nextItem(feasibleRoutes));
   	  
[jsonDecisionVariable.txt](https://github.com/MOEAFramework/MOEAFramework/files/1924850/jsonDecisionVariable.txt)

   	  JSONObject transitSchedule2 = (JSONObject) randRoutes.get("transitSchedule");
   	  JSONArray transitLine2 = transitSchedule2.getJSONArray("transitLine");
   	  
	   	if  (var!=null && var.length()>0 && randRoutes!=null && randRoutes.length()>0) {
			  
			  for (int i = 0; i < 1; i++) {
				 
				 transitLine1.remove(i);
				 transitLine1.put(transitLine2.get(i));
				 transitLine2.remove(i);
				 transitLine2.put(transitLine1.get(i));
				 	  
			  }
	  }
   	  
}
```

**Comment by Nobik2** [comment]
Thank you for your suggestion it works, this will now enable me to look closely at the algorithm.
