### ISSUE TITLE
Concurrent modification issue using Instrumenter

### ISSUE THREAD

**Issue by Leative** [MOEAFramework/MOEAFramework#180]
Hi everyone,

today I ran into a ConcurrentModificationException while the Instrumenter tried to instrument the algorithm.

`Exception in thread "main" java.util.ConcurrentModificationException
	at org.eclipse.emf.common.util.WeakInterningHashSet$1.hasNext(WeakInterningHashSet.java:785)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:612)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:607)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:613)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:654)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:643)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:786)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:804)
	at org.moeaframework.Executor.run(Executor.java:743)
	at uk.ac.kcl.optimisation.moea.MoeaOptimisation.runOptimisation(MoeaOptimisation.java:65)
	at uk.ac.kcl.optimisation.moea.MoeaOptimisation.execute(MoeaOptimisation.java:27)
	at uk.ac.kcl.interpreter.OptimisationInterpreter.start(OptimisationInterpreter.java:52)
	at uk.ac.kcl.ui.launch.RunOptimisation.run(RunOptimisation.java:74)
	at uk.ac.kcl.ui.launch.RunOptimisationBatch.main(RunOptimisationBatch.java:58)`

I am using MOEA with NSGAII for model optimization. That is, a Solution's main part is a model (more or less represented by a graph of nodes and edges). The WeakInterningHashSet is an implementation provided by the modeling framework EMF. So it seems that some model structure changed while iterating over those elements.

The algorithm ran without problems for about 900 executions. So conventional debugging might be painful. Maybe with your knowledge about the Instrumenter you can give me a hint on what the problem might be?

**Comment by dhadka** [comment]
Hi, thanks for reporting this bug!  I've committed a change that lets you exclude certain packages from the instrumenter.

You'll want to get the latest master branch and modify the Instrumenter code so that it calls `addExcludedPackage("org.eclipse")`.  This will prevent it from walking that class.  For example:

    Instrumenter instrumenter = new Instrumenter()
        .addExcludedPackage("org.eclipse")
        .withFrequency(100)
        .attachAll();

**Comment by Leative** [comment]
Thank you! 
Just to make me understand what's happening, why is the instrumenter traversing over the complete object tree? In the end, the data which is collected is MOEA specific. So I would have expected that only MOEA classes (or subclasses of those) need to be instrumented. For example, the algorithm. 
That information might help to decide which classes should be excluded.

**Comment by dhadka** [comment]
The original intent for having it traverse the entire object graph is so that custom Collectors could be implemented if a user creates their own MOEA or wants to collect data from some object outside the `org.moeaframework` package.

I suspect what's happening in your case is that the Collector is traversing the Population used by the MOEA, but then recursively inspects the contents of each Solution in the population.  I think it would be safe to exclude Solutions from inspection, since we already provide a way to enumerate the contents of a population, which should prevent conflicts like this with user-defined representations.

**Comment by Leative** [comment]
Thanks again for the explanation!
