### ISSUE TITLE
no provider for NSGAII - Instrumenter Error

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#183]
Hi @dhadka 

This code below which you helped me with the last time gave the error below:

```java
Exception in thread "main" org.moeaframework.core.spi.ProviderNotFoundException: no provider for SimulationBasedTransitOptimizationProblem
	at org.moeaframework.core.spi.ProblemFactory.getProblem(ProblemFactory.java:159)
	at playground.onnene.ga.RunSimulationBasedTransitOptimizationProblem.main(RunSimulationBasedTransitOptimizationProblem.java:168)
```
I then changed the first line in the code with my own problem, but I get the error below. 

``` java
Exception in thread "main" org.moeaframework.core.spi.ProviderNotFoundException: no provider for NSGAII
	at org.moeaframework.algorithm.StandardAlgorithms.getAlgorithm(StandardAlgorithms.java:331)
	at org.moeaframework.core.spi.AlgorithmFactory.instantiateAlgorithm(AlgorithmFactory.java:175)
	at org.moeaframework.core.spi.AlgorithmFactory.getAlgorithm(AlgorithmFactory.java:137)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:785)
	at org.moeaframework.Executor.run(Executor.java:743)
	at playground.onnene.ga.RunSimulationBasedTransitOptimizationProblem.main(RunSimulationBasedTransitOptimizationProblem.java:188)
Caused by: org.moeaframework.core.spi.ProviderLookupException: unable to find suitable variation operator
	at org.moeaframework.core.spi.OperatorFactory.lookupVariationHint(OperatorFactory.java:347)
	at org.moeaframework.core.spi.OperatorFactory.getVariation(OperatorFactory.java:182)
	at org.moeaframework.core.spi.OperatorFactory.getVariation(OperatorFactory.java:160)
	at org.moeaframework.algorithm.StandardAlgorithms.newNSGAII(StandardAlgorithms.java:415)
	at org.moeaframework.algorithm.StandardAlgorithms.getAlgorithm(StandardAlgorithms.java:271)
	... 5 more
```
I know I have defined a provider and variation operators so I dont know how to resolve this, please clarify it for me.  

 ```java
//Problem problem = ProblemFactory.getInstance().getProblem("DTLZ2_2");
Problem problem = new SimulationBasedTransitOptimizationProblem();
        
        OperatorFactory.getInstance().addProvider(new GA_OperatorProvider()); //Provider      
        String[] algorithms = { "NSGAII", "GDE3" };
        
        Instrumenter instrumenter = new Instrumenter()
				.withProblem(problem)
				.attachApproximationSetCollector();
		
        Executor executor = new Executor()
				.withProblem(problem)
				.withMaxEvaluations(10000)
				.withInstrumenter(instrumenter);
		
		  // Store the data and compute the reference set
 		Map<String, Accumulator> results = new HashMap<String, Accumulator>();
 		NondominatedPopulation referenceSet = new NondominatedPopulation();
 		
 		for (String algorithm : algorithms) {
 			referenceSet.addAll(executor.withAlgorithm(algorithm).run());
 			results.put(algorithm, instrumenter.getLastAccumulator());
 		}
 		
 		// Calculate the performance metrics using the reference set
 		QualityIndicator qi = new QualityIndicator(problem, referenceSet);
 		
 		for (String algorithm : algorithms) {
 			Accumulator accumulator = results.get(algorithm);
 			
 			System.out.println(algorithm);
			
 			for (int i = 0; i < accumulator.size("NFE"); i++) {
 				List<Solution> approximationSet = (List<Solution>)accumulator.get("Approximation Set", i);
 				qi.calculate(new NondominatedPopulation(approximationSet));
				
 				System.out.print("    ");
 				System.out.print(accumulator.get("NFE", i));
 				System.out.print(" ");
 				System.out.print(qi.getHypervolume());
 				System.out.println();
 			}
 			
 			System.out.println();
 		}
```

Secondly, how can I add create a problem provider for custom problems. 

Regards

**Comment by dhadka** [comment]
Hi, sorry you hit this issue.  Please make sure GA_OperatorProvider is correctly returning the operator hints for getMutationHint and getVariationHint.  They should return a string with the name of the operators, e.g., "sbx", or combination of operators, e.g., "sbx+pm", that it should use.  If you can provide the source code for GA_OperatorProvider, I can take a look.

**Comment by dhadka** [comment]
To define custom problems, you would create a ProblemProvider:

```java

public class MyProblemProvider extends ProblemProvider {
    public Problem getProblem(String name) {
        if (name.equalsIgnoreCase("myProblem")) {
            return new MyProblem();
        } else {
            return null;
        }
    }

    public NondominatedPopulation getReferenceSet(String name) {
        if (name.equalsIgnoreCase("myProblem")) {
            // If you don't have a reference set, return null.  But some functionality will be disabled.
            return new NondominatedPopulation(PopulationIO.readObjectives("myProblemRefSet.txt"));
        } else {
            return null;
        }
    }
}

**Comment by Nobik2** [comment]
@dhadka  thanks a lot for all your help, here is my operator provider,  it is for a custom problem and it works fine with the executor  but not with the instrumenter.

**Operator Provider**
```java
public class GA_OperatorProvider extends OperatorProvider {
	
	 @Override
	    public String getMutationHint(Problem problem) {
	        return null;
	    }

	    @Override
	    public String getVariationHint(Problem problem) {
	        return null;
	    }

	    @Override
	    public Variation getVariation(String name, Properties properties, Problem problem) {
	        
	        TypedProperties typedProperties = new TypedProperties(properties);

	        if (name.equalsIgnoreCase("MyCrossover")) {
	            return new Crossover(typedProperties.getDouble("MyCrossover.Rate", 1.0));
	        } else if (name.equalsIgnoreCase("MyMutation")) {
	            return new Mutation(typedProperties.getDouble("MyMutation.Rate", 0.2));
	        }

	        // No match, return null
	        return null;
	    }

}

```

**Executor**
   ```java
    NondominatedPopulation result = new Executor()
           .withProblemClass(SimulationBasedTransitOptimizationProblem.class)
            .withAlgorithm("NSGAII")
            .withProperty("operator", "MyCrossover+MyMutation")
           .withProperty("MyCrossover.Rate", 0.75)
            .withProperty("MyMutation.Rate", 0.25)
           .withProperty("populationSize", 10)        
            .withMaxEvaluations(10)
            .run();
```
