### ISSUE TITLE
runtime data collection for NSGA-II 

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#188]
Hi @dhadka 

I modified the code sample you gave me here #181, (see modified version below). When I run the code, the optimization runs fine but at the end when the runtime data should be written, I get two different errors: see below (I get the error at different run attempts not in a single run). The code worked fine for the "DTLZ2_2" problem as evidenced in your output, but I have not got any joy trying to apply it to my problem. The key objective is to be able to save the runtime data for my algorithm so that I can present that in a plot of sorts. Kindly, point me in the correct direction in order to achieve this.

```java
public static void main(String[] args) {
		
		//Problem problem = ProblemFactory.getInstance().getProblem("DTLZ2_2");
		ProblemFactory.getInstance().addProvider(new GA_ProblemProvider());
    	        Problem problem = ProblemFactory.getInstance().getProblem("SimulationBasedTransitOptimizationProblem");
    	        OperatorFactory.getInstance().addProvider(new GA_OperatorProvider());
		String[] algorithms = { "NSGAII" };
		
		Instrumenter instrumenter = new Instrumenter();
				instrumenter.withProblem(problem);
				instrumenter.attachApproximationSetCollector();
				instrumenter.attachElapsedTimeCollector();

		Executor executor = new Executor()
				.withProblem(problem)
				.withProperty("operator", "MyCrossover+MyMutation")
				.withProperty("MyCrossover.Rate", 0.75)
	                        .withProperty("MyMutation.Rate", 0.25)
	                        .withProperty("populationSize", 10)
				.withMaxEvaluations(10)
				.withInstrumenter(instrumenter);
				
		// Store the data and compute the reference set
		Map<String, Accumulator> results = new HashMap<String, Accumulator>();
		NondominatedPopulation referenceSet = new NondominatedPopulation();
	
		for (String algorithm : algorithms) {
			referenceSet.addAll(executor.withAlgorithm(algorithm).run());
			results.put(algorithm, instrumenter.getLastAccumulator());			
		}
		
		// Calculate the performance metrics using the reference set
		QualityIndicator qi = new QualityIndicator(problem, referenceSet);
		
		for (String algorithm : algorithms) {
			Accumulator accumulator = results.get(algorithm);
						
			for (int i = 0; i < accumulator.size("NFE"); i++) {
				List<Solution> approximationSet = (List<Solution>)accumulator.get("Approximation Set", i);
				qi.calculate(new NondominatedPopulation(approximationSet));				
				System.out.print("    ");
				System.out.print(accumulator.get("NFE", i));
				System.out.print(" ");
				System.out.print(qi.getHypervolume());
				System.out.println();
			}
			
			System.out.println();
		}
	}
```

```java
[NSGAII=org.moeaframework.analysis.collector.Accumulator@64026239]Exception in thread "main" java.lang.IllegalArgumentException: key not defined in accumulator: NFE
	at org.moeaframework.analysis.collector.Accumulator.size(Accumulator.java:121)
	at playground.onnene.ga.GA_Instrumenter.main(GA_Instrumenter.java:100)
```
```java
Exception in thread "main" java.lang.IllegalArgumentException: requires at least two solutions
	at org.moeaframework.core.indicator.Normalizer.calculateRanges(Normalizer.java:173)
	at org.moeaframework.core.indicator.Normalizer.<init>(Normalizer.java:81)
	at org.moeaframework.core.indicator.QualityIndicator.<init>(QualityIndicator.java:109)
	at playground.onnene.ga.GA_Instrumenter.main(GA_Instrumenter.java:91)
```

**Comment by dhadka** [comment]
Hi, you're getting the first error about the NFE key not found because the collection frequency is 100 by default but your max evaluations is 10, so it hasn't yet recorded any data.  If you add `.withFrequency(10)` to your instrumenter, that should let it collect one record.

Regarding the second error, the normalized metrics (e.g, Hypervolume) need at least two solutions in the reference set to compute the min/max bounds.  I suspect since you're only running for 10 evaluations, you might only have one solution in the final population.  Also, if your problem has constraints, make sure you have feasible solutions.  These metrics can't be calculated unless you have found feasible solutions.
