### ISSUE TITLE
NSGAII Parallelization Error

### ISSUE THREAD

**Issue by Nobik2** [MOEAFramework/MOEAFramework#191]
Hi @dhadka,

When I run my program with the `.distributeOn(x)` with `x > 1` or `.distributeOnAllCores()`, I get the error below. Is this to mean that I cannot parallelize the program on the MOEAframework? my decision variable function is also pasted below as the error shows the . Please give me your perspective on this and how I can possibly go around it. I 

Thank you

```java
Exception in thread "main" java.lang.NullPointerException
	at playground.onnene.ga.DecisionVariable.copy(DecisionVariable.java:63)
	at org.moeaframework.core.Solution.<init>(Solution.java:114)
	at org.moeaframework.util.distributed.FutureSolution.<init>(FutureSolution.java:54)
	at org.moeaframework.util.distributed.DistributedProblem.newSolution(DistributedProblem.java:139)
	at org.moeaframework.core.operator.RandomInitialization.initialize(RandomInitialization.java:59)
	at org.moeaframework.algorithm.AbstractEvolutionaryAlgorithm.initialize(AbstractEvolutionaryAlgorithm.java:97)
	at org.moeaframework.algorithm.AbstractAlgorithm.step(AbstractAlgorithm.java:159)
	at org.moeaframework.algorithm.PeriodicAction.step(PeriodicAction.java:108)
	at org.moeaframework.algorithm.PeriodicAction.step(PeriodicAction.java:108)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:816)
	at org.moeaframework.Executor.run(Executor.java:743)
	at playground.onnene.ga.RunSimulationBasedTransitOptimisationProblem.runSimulation(RunSimulationBasedTransitOptimisationProblem.java:163)
	at playground.onnene.ga.RunSimulationBasedTransitOptimisationProblem.main(RunSimulationBasedTransitOptimisationProblem.java:67)
```

```java
NondominatedPopulation offSpring = new Executor()
	        	.withSameProblemAs(instrumenter)
	            .withAlgorithm("NSGAII")
	            .withProperty("operator", "MyCrossover+MyMutation")
	            .withProperty("MyCrossover.Rate", 0.75)
	            .withProperty("MyMutation.Rate", 0.25)
	            .withProperty("populationSize", 100)
	            .withMaxEvaluations(5000)  
	            //.resetCheckpointFile()
	            .withCheckpointFile(checkPointFile)		  
	            .withCheckpointFrequency(100)
	            .withInstrumenter(instrumenter)     
	            .distributeOn(numThreads)
	            //.distributeOnAllCores()            
	            .run();
```

```java
public class DecisionVariable implements Variable{
	
    private static final long serialVersionUID = 1L;
    private JSONObject transitSchedule; 

    public DecisionVariable() {
    	super();   		
    }
    
    public DecisionVariable(JSONObject transitSchedule) {
		this();
		this.transitSchedule = transitSchedule;
    }
    
    public JSONObject getTransitSchedule() {
        return transitSchedule;
    }

    public void setTransitSchedule(JSONObject transitSchedule) {
        this.transitSchedule = transitSchedule;
    }

    @Override
    public Variable copy() {

        DecisionVariable v = new DecisionVariable();        
        v.setTransitSchedule(new JSONObject(this.getTransitSchedule().toString()));  //onnene.ga.DecisionVariable.copy(DecisionVariable.java:63)              
        return v;
    }

    @Override
    public void randomize() {
        transitSchedule = new ProblemUtils().getRandomTransitSchedule();
    }	
}
```

**Comment by dhadka** [comment]
The error seems to indicate that `this.getTransitSchedule()` is returning null.  If that's expected, then I think you just need to guard against the null reference:

```java

    @Override
    public Variable copy() {

        DecisionVariable v = new DecisionVariable();

        if (this.getTransitSchedule() != null) {
            v.setTransitSchedule(new JSONObject(this.getTransitSchedule().toString()));
        }

        return v;
    }
```
