### ISSUE TITLE
Properties() vs TypedProperties() - NSGAII

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#200]
@dhadka,

Please how can the code below adapted from this issue #199 be used for i)a custom problem version ii) that has no redefined reference set. I get the error below when I tried to do that. I am _guessing_ its because NSGAII is defined with `new Properties()`; while my custom variation operators are made with `TypedProperties()`. How can I resolve this?. 

P.S. I had to put together a reference set to get the code to work but I rather work without it as it is not standardized. 

**error**
```java
Exception in thread "main" org.moeaframework.core.spi.ProviderNotFoundException: no provider for NSGAII
	at org.moeaframework.algorithm.StandardAlgorithms.getAlgorithm(StandardAlgorithms.java:331)
	at org.moeaframework.core.spi.AlgorithmFactory.instantiateAlgorithm(AlgorithmFactory.java:175)
	at org.moeaframework.core.spi.AlgorithmFactory.getAlgorithm(AlgorithmFactory.java:137)
	at org.matsim.onnene.ga.InjectedPop.main(InjectedPop.java:64)
Caused by: org.moeaframework.core.spi.ProviderLookupException: unable to find suitable variation operator
	at org.moeaframework.core.spi.OperatorFactory.lookupVariationHint(OperatorFactory.java:347)
	at org.moeaframework.core.spi.OperatorFactory.getVariation(OperatorFactory.java:182)
	at org.moeaframework.core.spi.OperatorFactory.getVariation(OperatorFactory.java:160)
	at org.moeaframework.algorithm.StandardAlgorithms.newNSGAII(StandardAlgorithms.java:415)
	at org.moeaframework.algorithm.StandardAlgorithms.getAlgorithm(StandardAlgorithms.java:271)
	... 3 more
```

**code**

```java
		ProblemFactory.getInstance().addProvider(new GA_ProblemProvider());
		Problem problem = ProblemFactory.getInstance().getProblem("SimulationBasedTransitOptimisationProblem");
		
		Algorithm algorithm = AlgorithmFactory.getInstance().getAlgorithm("NSGAII", new Properties(), problem);
		OperatorFactory.getInstance().addProvider(new GA_OperatorProvider());
		
		//NondominatedPopulation referenceSet = new NondominatedPopulation(PopulationIO.readObjectives(new File("./output/SBO_input/problemRefSet.pf"))); // This is not a standard reference set, I rather work without it
		
		QualityIndicator qi = new QualityIndicator(problem, referenceSet);
		
		File checkpointFile = new File("./output/SBO_input/injectedcheckpoint.dat");
		File outputFile = new File("./output/SBO_input/injectedOutput.txt");
		
		if (checkpointFile.exists()) { 
			LOG.info("Using checkpoint file!");
		}
			
		Checkpoints checkpoint = new Checkpoints(algorithm, checkpointFile, 100);
		
		try (FileWriter writer = new FileWriter(outputFile, true)) {
			while (checkpoint.getNumberOfEvaluations() < 10000) {
				checkpoint.step();
				qi.calculate(checkpoint.getResult());
				
				writer.write(checkpoint.getNumberOfEvaluations() + " "
						+ qi.getGenerationalDistance() + " "
						+ qi.getHypervolume()
						+ System.lineSeparator());
			}
		}

```

**Comment by dhadka** [comment]
I think you need to move this line:

    OperatorFactory.getInstance().addProvider(new GA_OperatorProvider());

before calling `getAlgorithm`.  (I'm working on an example to save the data and then calculate the reference set and metrics after all the data is collected).

**Comment by Nobik2** [comment]
The error persists after moving that line

**Comment by dhadka** [comment]
Please try the following.  This also demonstrates how you can pass in the TypedProperties:

```java

		TypedProperties properties = new TypedProperties();
		properties.setString("operator", "MyCrossover+MyMutation");
		properties.setDouble("MyCrossover.Rate", 0.75);
		properties.setDouble("MyMutation.Rate", 0.25);
		properties.setInt("populationSize", 10);
		
		OperatorFactory.getInstance().addProvider(new GA_OperatorProvider());
		Algorithm algorithm = AlgorithmFactory.getInstance().getAlgorithm("NSGAII", properties.getProperties(), problem);
```

**Comment by Nobik2** [comment]
@dhadka, thanks, now it runs, but it writes the data at the end of the run and if the run breaks somewhere in the middle, the previous data is lost, which is the former behavior with the `instrumenter`. What I want to achieve is to be able to collect that data as it run so that in case of an unexpected break previously collected data is not lost.

**Comment by dhadka** [comment]
This demonstrates how to run several algorithms saving their Pareto sets to a file, compute a reference set from those files, and calculating the metrics using that reference set:

```java

	public static void main(String[] args) throws Exception {
		// Step 1 - Run the algorithm(s).  If running multiple algorithms, save to separate files.
		Problem problem = ProblemFactory.getInstance().getProblem("DTLZ2_2");
		
		TypedProperties properties = new TypedProperties();
		properties.setInt("populationSize", 10);
		
		int maxNFE = 10000;
		String[] algorithmNames = new String[] { "NSGAII", "GDE3" };
		List<File> outputFiles = new ArrayList<File>();
		
		for (String algorithmName : algorithmNames) {
			System.out.println("Evaluating " + algorithmName + "...");
			
			Algorithm algorithm = AlgorithmFactory.getInstance().getAlgorithm("NSGAII", properties.getProperties(), problem);

			File checkpointFile = new File("checkpoint_" + algorithmName + ".chkpt");
			File outputFile = new File("output_" + algorithmName + ".set");
			
			if (checkpointFile.exists()) {
				System.out.println("Using checkpoint file for " + algorithmName + "!");
			}
			
			CheckpointAndOutputResult wrapper = new CheckpointAndOutputResult(algorithm, checkpointFile, outputFile, 100);
	
			while (wrapper.getNumberOfEvaluations() < maxNFE) {
				wrapper.step();
			}
			
			outputFiles.add(outputFile);
		}
		
		// Step 2 - Compute the reference set.
		System.out.println("Computing reference set...");
		File referenceSetFile = new File("output_refset.ref");
		
		ResultFileMerger.main(
				ArrayUtils.addAll(
					new String[] {
						"--dimension", Integer.toString(problem.getNumberOfObjectives()),
						"--output", referenceSetFile.getAbsolutePath()
					},
					outputFiles.stream().map(f -> f.getAbsolutePath()).collect(Collectors.toList()).toArray(new String[0])));
		
		// Step 3 - Evaluate the metrics.
		for (File outputFile : outputFiles) {
			System.out.println("Calculating metrics for " + outputFile + "...");
			
			ResultFileEvaluator.main(new String[] {
					"--dimension", Integer.toString(problem.getNumberOfObjectives()),
					"--input", outputFile.getAbsolutePath(),
					"--output", new File(outputFile.getParentFile(), outputFile.getName().replace(".set", ".metrics")).getAbsolutePath(),
					"--reference", referenceSetFile.getAbsolutePath(),
					"--force"
			});
		}

		System.out.println("Finished!");
	}
	
	public static class CheckpointAndOutputResult extends Checkpoints {
		private final ResultFileWriter writer;
		
		public CheckpointAndOutputResult(Algorithm algorithm, File stateFile, File outputFile,
				int frequency) throws IOException {
			super(algorithm, stateFile, frequency);
			writer = new ResultFileWriter(algorithm.getProblem(), outputFile, true);
		}

		@Override
		public void doAction() {
			// Write the result to the output file
			try {
				Properties resultInfo = new Properties();
				resultInfo.setProperty("NFE", Integer.toString(algorithm.getNumberOfEvaluations()));
	
				writer.append(new ResultEntry(algorithm.getResult(), resultInfo));
			}
			catch (IOException e) {
				throw new FrameworkException(e);
			}
			
			// Call super to save the checkpoint file
			super.doAction();
		}

		@Override
		public void terminate() {
			super.terminate();
			writer.close();
		}
	}
```

**Comment by Nobik2** [comment]
Thanks so much David, I am presently testing it with my problem.
