### ISSUE TITLE
Instrumenter Error!!

### ISSUE THREAD

**Issue by rrreza** [MOEAFramework/MOEAFramework#218]
Only when I add "Instrumenter" ,an error occurs!
```

Instrumenter instrumenter = new Instrumenter()
     .withProblem(problemName)
     .attachAll();
 
   Executor executor = new Executor()
     .withProblem(problemName)
     .withAlgorithm(algorithmName)
     .withMaxEvaluations(numberOfEvaluations)
     .withInstrumenter(instrumenter)
     .run();

```
Error:
Exception in thread "main" java.lang.IllegalArgumentException: no reference set available
	at org.moeaframework.ProblemBuilder.getReferenceSet(ProblemBuilder.java:274)
	at org.moeaframework.Instrumenter.getReferenceSet(Instrumenter.java:549)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:686)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:804)
	at org.moeaframework.Executor.run(Executor.java:743)
	at Main.main(Main.java:29)

**Comment by dhadka** [comment]
Please see issue #181, which discusses a similar issue.
