### ISSUE TITLE
IndexOutOfBoundsException when using NSGA-III

### ISSUE THREAD

**Issue by MisooKim** [MOEAFramework/MOEAFramework#238]
When I use NSGAIII for optimization, the optimization was failed.

**Mave Version**
Group: org.moeaframework
Artifact: moeaframework
Version: 2.12

**Setting**
Num of objectives = 6
Num of population = 20
Num of Iteration = 15,000
Num of genes = 12
Type of Gene = binary (0 or 1)
Algorithm = NSGAIII
Crossover(Prob,) = 1-point (0.3)
Mutation(Prob,) = binary mutation (0.01)

**Stack Trace**
```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 210
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.moeaframework.algorithm.ReferencePointNondominatedSortingPopulation.associateToReferencePoint(ReferencePointNondominatedSortingPopulation.java:560)
	at org.moeaframework.algorithm.ReferencePointNondominatedSortingPopulation.truncate(ReferencePointNondominatedSortingPopulation.java:638)
	at org.moeaframework.algorithm.ReferencePointNondominatedSortingPopulation.truncate(ReferencePointNondominatedSortingPopulation.java:691)
	at org.moeaframework.algorithm.NSGAII.iterate(NSGAII.java:148)
	at org.moeaframework.algorithm.AbstractAlgorithm.step(AbstractAlgorithm.java:161)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:816)
	at org.moeaframework.Executor.run(Executor.java:743)
	at temp.core.GA.getNearOptimalQueryForGenQ(GA.java:654)
	at exp.GenQExp.main(GenQExp.java:271)
```

**Comment by dhadka** [comment]
Hi, thanks for reporting this.  Can you please check if any of your objectives are positive infinity?  A quick way to check is to add `System.out.println(Arrays.toString(objectives))` in your evaluate method.

If not, would you be able to share your code, or maybe a simplified version that reproduces this error?  If you don't want to share publicly, you can send it to me directly at support@moeaframework.org

Thanks!

**Comment by MisooKim** [comment]
Based on your advice, I identified that some objectives were returned the NaN values, so the populations couldn't be compared with each other.

Thank you.
