### ISSUE TITLE
IndexOutOfBoundsException for MersenneTwister

### ISSUE THREAD

**Issue by chelsmpeterson** [MOEAFramework/MOEAFramework#264]
I am generating threads for each random sample and seed combination in a for loop, and I got this error for 2/9 threads but not the others. The random seeds I am using are 1, 2, and 3 with eMOEA. Do you know what could be causing this error?

Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: Index 624 out of bounds for length 624
        at org.apache.commons.math3.random.MersenneTwister.next(MersenneTwister.java:252)
        at org.apache.commons.math3.random.BitsStreamGenerator.nextDouble(BitsStreamGenerator.java:89)
        at org.apache.commons.math3.random.RandomAdaptor.nextDouble(RandomAdaptor.java:99)
        at org.moeaframework.core.PRNG.nextDouble(PRNG.java:131)
        at org.moeaframework.core.variable.RealVariable.randomize(RealVariable.java:166)
        at org.moeaframework.core.operator.RandomInitialization.initialize(RandomInitialization.java:62)
        at org.moeaframework.algorithm.AbstractEvolutionaryAlgorithm.initialize(AbstractEvolutionaryAlgorithm.java:97)
        at org.moeaframework.algorithm.AbstractAlgorithm.step(AbstractAlgorithm.java:159)
        at org.moeaframework.algorithm.PeriodicAction.step(PeriodicAction.java:108)
        at org.moeaframework.Executor.runSingleSeed(Executor.java:827)
        at org.moeaframework.Executor.run(Executor.java:748)
        at ScriptsSA.RunSA.run(RunSA.java:166)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by dhadka** [comment]
Please see the suggestion in https://github.com/MOEAFramework/MOEAFramework/issues/100.  TL;DR: The random number generator code is not thread-safe and needs to be wrapped in a `SynchronizedRandomGenerator`.

**Comment by chelsmpeterson** [comment]
Ok, I tried that and got this error:

error: SynchronizedMersenneTwister() has private access in SynchronizedMersenneTwister

Maybe I am not importing it correctly?

**Comment by dhadka** [comment]
Ah, sorry...that should be:

```
PRNG.setRandom(SynchronizedMersenneTwister.getInstance());
```
