### ISSUE TITLE
NSGAII - Properties passed to Executor ignored when calling NSGAII constructor

### ISSUE THREAD

**Issue by Matthias-Sleurink** [MOEAFramework/MOEAFramework#359]
I'm trying to get up to speed  at using this library by implementing some example problems. For one of my problems I found that the properties that I set on an Executor are ignored when calling the NSGAII constructor.

I'm using this dependency via Maven, depending on version 3.4 from maven central.

For context, this is what my Solution looks like: (I have some amount of ints, and then a binary of the same length that adjusts the meaning that these ints have.)

```java
var solution = new Solution(AMOUNT_OF_ACTIONS+1, 1);
for (int i = 0; i < AMOUNT_OF_ACTIONS; i++) {
    solution.setVariable(i, EncodingUtils.newInt(0, AMOUNT_OF_SPACES));
}

solution.setVariable(AMOUNT_OF_ACTIONS, EncodingUtils.newBinary(AMOUNT_OF_ACTIONS));

return solution;
```

Now, this is my run configuration:

```java
var results = new Executor()
    .withProperty("operator", "2x")
    .withAlgorithm("NSGAII")
    .withProblemClass(WordReversalProblem.class)
    .withMaxEvaluations(10_000)
    .run();
```

When I run this problem I get the following error:
```java
Exception in thread "main" org.moeaframework.core.spi.ProviderNotFoundException: no provider for NSGAII
	at org.moeaframework.core.spi.RegisteredAlgorithmProvider.getAlgorithm(RegisteredAlgorithmProvider.java:66)
	at org.moeaframework.core.spi.AlgorithmFactory.instantiateAlgorithm(AlgorithmFactory.java:126)
	at org.moeaframework.core.spi.AlgorithmFactory.getAlgorithm(AlgorithmFactory.java:103)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:806)
	at org.moeaframework.Executor.run(Executor.java:751)
	at ut.mat.trainingAssignments.WordReversal.RunWordReversal.main(RunWordReversal.java:14)
Caused by: java.lang.IllegalArgumentException: variation can not be null
	at org.moeaframework.core.configuration.Validate.notNull(Validate.java:159)
	at org.moeaframework.algorithm.AbstractEvolutionaryAlgorithm.setVariation(AbstractEvolutionaryAlgorithm.java:194)
	at org.moeaframework.algorithm.NSGAII.setVariation(NSGAII.java:167)
	at org.moeaframework.algorithm.AbstractEvolutionaryAlgorithm.<init>(AbstractEvolutionaryAlgorithm.java:89)
	at org.moeaframework.algorithm.NSGAII.<init>(NSGAII.java:96)
	at org.moeaframework.algorithm.NSGAII.<init>(NSGAII.java:73)
	at org.moeaframework.algorithm.DefaultAlgorithms.lambda$fromProblem$0(DefaultAlgorithms.java:90)
	at org.moeaframework.core.spi.RegisteredAlgorithmProvider.getAlgorithm(RegisteredAlgorithmProvider.java:64)
	... 5 more

Process finished with exit code 1
```

I did some digging around, and found what I believe to be the cause of the problem:

1. When I call `withProperty("operator", "2x")` my property is set in the `TypedProperties` instance of the `Executor`.
2. When I call `run()` the following happens:
3. `getAlgorithm(String name, TypedProperties properties, Problem problem)` finds the constructor and calls it with the properties object that has my setting from above.
4. Through some function applications we reach `private <T extends Algorithm & Configurable> BiFunction<TypedProperties, Problem, Algorithm> fromProblem(Function<Problem, T> supplier)`
5. This calls the constructor without passing in any properties.
6. This constructor (NSGAII Line 72) thus seeks out the default value for the "Variation" parameter using `OperatorFactory.getInstance().getVariation(problem)`.
7. This returns null.
8. Through some more constructors and methods we eventually reach the `Validate.notNull` call for this property.
9. This errors out since it is actually null.

Just below the call from number 5 above, the properties _would_ have been applied, had the default value not been an invalid one. (DefaultAlgorithms line 91: `algorithm.applyConfiguration(properties);`)

So in essence, as far as I understand, because there is no default value registered for my Solution setup, the validator throws an exception, which, if the properties that I actually set up had been used to call the constructor, would not have needed to happen.

Or in other words, if the default value for a property does not pass the Validation, one cannot set a non-default value.

I hope this is enough information to solve this issue. If you need more context don't hesitate to ask.

**Comment by dhadka** [comment]
Thanks for reporting this.  I believe https://github.com/MOEAFramework/MOEAFramework/pull/360 will fix it.

**Comment by Matthias-Sleurink** [comment]
Wow, thanks for the fast response. Should that indeed fix it. When do you think it will be in a release?

**Comment by dhadka** [comment]
The fix is merged.  If you're interested in trying it out before it gets released, you can download the build artifacts - https://github.com/MOEAFramework/MOEAFramework/suites/11679060331/artifacts/607081287 - which has the MOEAFramework JAR file.

Then update `pom.xml` to point to this local file:

```
<dependency>
    <groupId>org.moeaframework</groupId>
    <artifactId>moeaframework</artifactId>
    <version>3.4</version>
    <scope>system</scope>
    <systemPath>${project.basedir}/src/main/resources/MOEAFramework-3.4.jar</systemPath>
</dependency>
```

**Comment by Matthias-Sleurink** [comment]
To confirm, this fix worked on my side as well. I indeed had to adjus my dependency to the Demo jar. Thanks for your help.
