### ISSUE TITLE
About PESA2

### ISSUE THREAD

**Issue by zhoudiprivateChina** [MOEAFramework/MOEAFramework#67]
Hi, it's me again. :)
It seems to have something wrong when i run PESA2 on WFG2_4, as well as WFG4_4 and nearly all the 4-objective WFG: 

Exception in thread "main" org.apache.commons.math3.exception.MathArithmeticException: arithmetic exception: overflow: base (256): exponent (4)
    at org.apache.commons.math3.util.ArithmeticUtils.mulAndCheck(ArithmeticUtils.java:533)
    at org.apache.commons.math3.util.ArithmeticUtils.pow(ArithmeticUtils.java:666)
    at org.moeaframework.core.AdaptiveGridArchive.<init>(AdaptiveGridArchive.java:92)
    at org.moeaframework.algorithm.PESA2.<init>(PESA2.java:83)
    at org.moeaframework.algorithm.StandardAlgorithms.newPESA2(StandardAlgorithms.java:726)
    at org.moeaframework.algorithm.StandardAlgorithms.getAlgorithm(StandardAlgorithms.java:242)
    at org.moeaframework.core.spi.AlgorithmFactory.instantiateAlgorithm(AlgorithmFactory.java:175)
    at org.moeaframework.core.spi.AlgorithmFactory.getAlgorithm(AlgorithmFactory.java:137)
    at org.moeaframework.Executor.runSingleSeed(Executor.java:772)
    at org.moeaframework.Executor.runSeeds(Executor.java:709)
    at Example2.main(Example2.java:49)

**Comment by dhadka** [comment]
It looks like the default value for the `bisections` parameter is too large for problems with 4 or more objectives.  8 bisections produces 2^8 = 256 divisions along each objective, which results in a grid with 256^4 cells.  This is larger than 2^32, the size of an integer variable, causing the arithmetic overflow exception.

You can try running with fewer bisections:

```java

new Executor()
    .withAlgorithm("PESA2")
    .withProperty("bisections", 6)
    ...
```

I'll probably need to scale the default value as the number of objectives increases.
